language: java

jdk:
  - openjdk8
  
after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
  
notifications:
  email:
    recipients:
      - builds@starchartlabs.org
    on_success: change
    on_failure: always
