language: java

jdk:
  - oraclejdk8
  
after_success:
  - ./gradlew buildBom
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*_bdio.jsonld

notifications:
  email:
    recipients:
      - corona.ide.dev@gmail.com
    on_success: change
    on_failure: always
